// AUTO-GENERATED — do not edit manually.
// Re-generated by scripts/generate-preview-manifest.mjs
// To update, add/remove .webp files in public/preview/ and restart dev server.

export const PREVIEW_IMAGES: string[] = [
  "/preview/preview1.webp",
  "/preview/preview2.webp",
  "/preview/preview3.webp",
  "/preview/preview4.webp",
  "/preview/preview5.webp",
  "/preview/preview6.webp"
]
