// AUTO-GENERATED — do not edit manually.
// Re-generated by scripts/generate-preview-manifest.mjs
// To update, add/remove .webp files in public/preview/ and restart dev server.

export const PREVIEW_IMAGES: string[] = [
  "/preview/01 copy 2.webp",
  "/preview/01 copy 3.webp",
  "/preview/01 copy 4.webp",
  "/preview/01 copy 5.webp",
  "/preview/01 copy.webp",
  "/preview/01.webp"
]
